name: my_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10.8
  - pandas==2.2.2
  - numpy==1.26.4
  - matplotlib==3.9.2
  - plotly==6.1.2
  - watermark==2.4.3
  - openpyxl==3.1.5
  - geopandas==1.1.0
  - imageio==2.37.0
  - Cartopy==0.24.1
  - pip:
    - pandapower

